#!/bin/bash
# My first script

echo "Validation de plusiers XML-DTD"

echo "Test Validation nº1"
echo
echo "Validation d'un fichier XML avec un fichier DTD avec que de declaration d'elements"
./analyse Test/rap1.xml
echo
echo

echo "Test Validation nº2"
echo
echo "Validation d'un fichier XML avec un fichier DTD avec que de declaration d'elements et attributes melangés"
./analyse Test/rap2.xml
echo
echo

echo "Test Validation nº3"
echo
echo "Validation d'un fichier XML avec un fichier DTD un peu plus complique,avec des cardinalites [0...n] et une structure données en forme d'arbre."
./analyse -s Test/rap4.xml Test/rap4.xsl
echo
echo

echo "Test Validation nº4"
echo
echo "Fichier xml non valide."
./analyse Test/non_valide.xml
echo
echo

echo "Test Validation nº5"
echo
echo "Fichier ne correspondant pas à la DTD."
./analyse Test/not_dtd_compliant.xml
echo
echo


echo "Test Validation nº6"
echo
echo "DTD non valide."
./analyse -d Test/non_valide.dtd
echo
echo


